### ISSUE TITLE
Better BOM

### ISSUE THREAD

**Issue by lazaj** [Board-Folk/Commodore-PC10-III-Reproduction#1]
First of all thanks for your job.

It would be great to provide a BOM with manufacturer and parts number.
A lot of components lacks unit, value ...
RMC on Youtube has build a board, so I think that you have a more complete BOM.

**Comment by lazaj** [comment]
C506, C509, C510, C701, C704, C705, C706, C707, C708, C709, C710, C711, C712, C713, C714, C715, C716, C717, C718, C719, C723, C724, C725, C726, C747, C748, C753, C757, C760, C761, C762, C770, C772, C775, C777, C778, C800, C802, C803 have value .1 what is the unit pf, uf ?

**Comment by lazaj** [comment]
idem for C508 .22 pf uf ?

**Comment by lazaj** [comment]
EMI401, EMI402, EMI403, EMI404, EMI405, EMI406, EMI407, EMI408, EMI409, EMI410, EMI411, EMI412, EMI413, EMI414, EMI415, EMI416, EMI417, EMI418, EMI419, EMI420, EMI421, EMI422, EMI423, EMI424, EMI425

FB104, FB105, FB601, FB602, FB604, FB605, FB606, FB607, FB608, FB609, FB610, FB611

EMI101, EMI102, EMI105, EMI607, EMI610, EMI611, EMI612, EMI613

RMC in its video used new components.
It is therefore possible to better define these components.

**Comment by lazaj** [comment]
I am an electronic and embedded software engineer. I am a trainer for Kicad.
So I can help you improve the BOM.
I need this information to restore my PC10 6C

**Comment by grandoldian** [comment]
Hi Lazaj,
As it says on the home page for the repo, we won't provide a supplier BOM for the boards as it changes all the time. It changed within the time we did the original builds. Things go out of stock, stop being sold etc etc. As for component values, we used the original 5.7 schematics occasionally changing for components found on real boards and modified where we could for rev 6. This isn't guaranteed to be correct. As you have one you can check your original board. In reference to the Commodore terminology, the capacitors in simple terms 0.1 means 100nF and 0.22 means 220nF.
The grounded 3 pin EMI filters we'd suggest you go for 100pF (101), larger kill the signals somewhat. The ferrite beads, some have used the ones found on AliExpress.
Ian.
